/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

{u"keypress", nullptr, u" ", u"shift", u"cmd_scrollPageUp"},
    {u"keypress", nullptr, u"w", u"control", u"cmd_deleteWordBackward"},
    {u"keypress", nullptr, u"u", u"control", u"cmd_deleteToBeginningOfLine"},
    {u"keypress", nullptr, u"k", u"control", u"cmd_deleteToEndOfLine"},
    {u"keypress", u"VK_RIGHT", nullptr, nullptr, u"cmd_moveRight"},
    {u"keypress", u"VK_LEFT", nullptr, u"control", u"cmd_selectLeft"},
    {u"keypress", u"VK_RIGHT", nullptr, u"control", u"cmd_selectRight"},
    {u"keypress", u"VK_UP", nullptr, nullptr, u"cmd_moveUp"},
    {u"keypress", u"VK_DOWN", nullptr, nullptr, u"cmd_moveDown"},
    {u"keypress", u"VK_UP", nullptr, u"control", u"cmd_selectUp"},
    {u"keypress", u"VK_DOWN", nullptr, u"control", u"cmd_selectDown"},
    {u"keypress", u"VK_LEFT", nullptr, u"shift", u"cmd_wordPrevious"},
    {u"keypress", u"VK_RIGHT", nullptr, u"shift", u"cmd_wordNext"},
    {u"keypress", u"VK_LEFT", nullptr, u"shift,control", u"cmd_selectWordPrevious"},
    {u"keypress", u"VK_RIGHT", nullptr, u"shift,control", u"cmd_selectWordNext"},
    {u"keypress", u"VK_BACK", nullptr, u"shift", u"cmd_deleteWordBackward"},
    {u"keypress", u"VK_HOME", nullptr, nullptr, u"cmd_beginLine"},
    {u"keypress", u"VK_END", nullptr, nullptr, u"cmd_endLine"},
    {u"keypress", u"VK_HOME", nullptr, u"control", u"cmd_selectBeginLine"},
    {u"keypress", u"VK_END", nullptr, u"control", u"cmd_selectEndLine"},
    {u"keypress", u"VK_HOME", nullptr, u"shift,control", u"cmd_selectTop"},
    {u"keypress", u"VK_END", nullptr, u"shift,control", u"cmd_selectBottom"},
    {u"keypress", u"VK_HOME", nullptr, u"shift", u"cmd_moveTop"},
    {u"keypress", u"VK_END", nullptr, u"shift", u"cmd_moveBottom"},
    {u"keypress", u"VK_PAGE_UP", nullptr, nullptr, u"cmd_movePageUp"},
    {u"keypress", u"VK_PAGE_DOWN", nullptr, nullptr, u"cmd_movePageDown"},
    {u"keypress", u"VK_PAGE_UP", nullptr, u"control", u"cmd_selectPageUp"},
    {u"keypress", u"VK_PAGE_DOWN", nullptr, u"control", u"cmd_selectPageDown"},
    {u"keypress", nullptr, u"d", u"shift,control", u"cmd_copy"},
    {u"keypress", nullptr, u"d", u"control", u"cmd_cut"},
    {u"keypress", nullptr, u"y", u"control", u"cmd_paste"},
    {u"keypress", nullptr, u"y", u"accel,shift", u"cmd_pasteNoFormatting"},
    {u"keypress", nullptr, u"_", u"control", u"cmd_undo"},
    {u"keypress", nullptr, u"_", u"control,shift", u"cmd_redo"},
